### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by suzeyanzhu** [nomi-san/balance-buff-viewer#3]
i need Latest version，If you don't have time to update, please tell me how to update the version data and change the regional language. Thank you

**Comment by nomi-san** [comment]
I have updated it to v13.16. I will provide a method that allows other update it from outside soon.

You can follow the building guide in readme and these setps to update locally:

0. Delete your `balance-buff-viewer.js` first
1. Clone this repo in your plugins folder
2. Install npm packages: `pnpm i`
3. Craw balance data: `pnpm crawl`
4. Build it: `pnpm build`

To add your trans/locales, take a look at [src/trans.json](https://github.com/nomi-san/balance-buff-viewer/blob/main/src/trans.json).
The `_locales` array should match your target locale, e.g. to support Brazilian:

```json
  "_locales": [
    "pt-BR"
  ],
```

However, you should use the DevTools to get exact locale/language.

**Comment by suzeyanzhu** [comment]
> I have updated it to v13.16. I will provide a method that allows other update it from outside soon.
> 
> You can follow the building guide in readme and these setps to update locally:
> 
> 0. Delete your `balance-buff-viewer.js` first
> 1. Clone this repo in your plugins folder
> 2. Install npm packages: `pnpm i`
> 3. Craw balance data: `pnpm crawl`
> 4. Build it: `pnpm build`
> 
> To add your trans/locales, take a look at [src/trans.json](https://github.com/nomi-san/balance-buff-viewer/blob/main/src/trans.json). The `_locales` array should match your target locale, e.g. to support Brazilian:
> 
> ```json
>   "_locales": [
>     "pt-BR"
>   ],
> ```
> 
> However, you should use the DevTools to get exact locale/language.



> I have updated it to v13.16. I will provide a method that allows other update it from outside soon.
> 
> You can follow the building guide in readme and these setps to update locally:
> 
> 0. Delete your `balance-buff-viewer.js` first
> 1. Clone this repo in your plugins folder
> 2. Install npm packages: `pnpm i`
> 3. Craw balance data: `pnpm crawl`
> 4. Build it: `pnpm build`
> 
> To add your trans/locales, take a look at [src/trans.json](https://github.com/nomi-san/balance-buff-viewer/blob/main/src/trans.json). The `_locales` array should match your target locale, e.g. to support Brazilian:
> 
> ```json
>   "_locales": [
>     "pt-BR"
>   ],
> ```
> 
> However, you should use the DevTools to get exact locale/language.

very Thanks
