### ISSUE TITLE
Can you update so non rank game can get the buff/nerf info?

### ISSUE THREAD

**Issue by KanNinChun** [nomi-san/balance-buff-viewer#6]
Hmm. sorry, but how can i use the plugin, since it doesn't work for me,
![image](https://github.com/nomi-san/balance-buff-viewer/assets/97720349/680c8a6d-7922-4e8a-942e-05e0193e277d)

**Comment by nomi-san** [comment]
> non rank game

Currently, it does not support gamemode out of ARAM and AR/URF.

> Hmm. sorry, but how can i use the plugin, since it doesn't work for me.

The title is too confusing with your issue content.

Have you tested it on a custom ARAM champ select?
There was a bug that sometimes the tooltip would not show up, you have to restart the client to get it to work.

**Comment by KanNinChun** [comment]
sorry, but can not get it to work, i restart it for muti times. still no hope :(

**Comment by nomi-san** [comment]
Let's create a custom ARAM and pick a random champ, then open the **DevTools** by pressing <kbd>F12</kbd> or <kbd>Ctrl Shift I</kbd>, nagivate to **Console** tab and check the log.

If you see these lines, so it works correctly but you are facing the mentioned visible bug above.

```
MOUNT 0
MOUNT 1
MOUNT 2
MOUNT 3
````

Otherwise, send me your debug.log in the client folder.

**Comment by KanNinChun** [comment]
[debug.log](https://github.com/nomi-san/balance-buff-viewer/files/13060885/debug.log)

**Comment by nomi-san** [comment]
I see the log, and dont know what did you do without reading the installation guide?

```
Failed to load plugin "balance-buff-viewer-main/index.js"
```

Please delete this "balance-buff-viewer-main" folder, then download my "balance-buff-viewer-main.js" and put it in the plugins folder.

```
pengu/
  |__plugins/
    |__balance-buff-viewer-main      ❌
      |__index.js                    ❌
    |__balance-buff-viewer-main.js   ✅

```

**Comment by KanNinChun** [comment]
my bad dude! Fixed, thanks for your help!
